# Generated by Django 2.2.19 on 2023-04-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20230403_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость товара в корзине'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='weight_nmb',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общий вес товаров в корзине'),
        ),
    ]
