# Generated by Django 2.2.19 on 2023-04-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_productinorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name': 'Товар в машине', 'verbose_name_plural': 'Товары в машине'},
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsincart', to='products.Product', verbose_name='Товар в машине'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость товара в машине'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='weight_nmb',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общий вес товаров в машине'),
        ),
    ]
