# Generated by Django 2.2.19 on 2023-05-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20230419_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='nmb',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=9, verbose_name='Количество'),
        ),
    ]
