# Generated by Django 2.2.19 on 2023-05-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20230523_1647'),
        ('orders', '0008_auto_20230523_1527'),
    ]

    operations = [
    ]
