# Generated by Django 2.2.19 on 2023-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230405_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
