# Generated by Django 2.2.19 on 2023-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230418_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Доп. скидка клиента в процентах'),
        ),
    ]
