# Generated by Django 2.2.19 on 2023-03-10 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=250, verbose_name='Группа товаров')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('price_tonn', models.IntegerField(verbose_name='Цена за тонну')),
                ('base_price', models.IntegerField(verbose_name='Базовая цена')),
                ('coeff', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Коэфф. пересчета')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('thickness', models.CharField(max_length=50, verbose_name='Толщина')),
                ('area', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Квадратные метры')),
                ('price_item', models.IntegerField(verbose_name='Цена за штуку')),
            ],
            options={
                'verbose_name': 'Лист',
                'verbose_name_plural': ' Листы',
                'ordering': ['-base_price'],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductNotList',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('parameter', models.CharField(max_length=50, verbose_name='Параметры, марка стали')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('price_metr', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за п/м')),
            ],
            options={
                'verbose_name': 'Товар не лист',
                'verbose_name_plural': ' Товары не листы',
                'ordering': ['-base_price'],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Категория товаров')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.Category', verbose_name='Группа товаров')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_not_list', to='products.Subcategory', verbose_name='Категория товара'),
        ),
    ]
