# Generated by Django 2.2.19 on 2023-03-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_item',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='Цена за ед.(п/м или шт.)'),
        ),
    ]
