# Generated by Django 2.2.19 on 2023-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlist',
            options={'verbose_name': 'Товар лист', 'verbose_name_plural': 'Товары Листы'},
        ),
        migrations.AlterModelOptions(
            name='productnotlist',
            options={'verbose_name': 'Товар не лист', 'verbose_name_plural': 'Товары не листы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Квадратные метры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(default=0, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parameter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Параметры, марка стали'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_item',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Цена за ед.(п/м или шт.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Толщина'),
        ),
    ]
