# Generated by Django 2.2.19 on 2023-03-06 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.CharField(max_length=50, verbose_name='Толщина')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('area', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Квадратные метры')),
                ('base_price', models.IntegerField(verbose_name='Базовая цена')),
                ('coeff', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Коэфф. пересчета')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_list', to='products.Subcategory', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Лист',
                'verbose_name_plural': ' Листы',
                'ordering': ['-base_price'],
            },
        ),
        migrations.CreateModel(
            name='ProductNotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('parameter', models.CharField(max_length=50, verbose_name='Параметры, марка стали')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('base_price', models.IntegerField(verbose_name='Базовая цена')),
                ('coeff', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Коэфф. пересчета')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_not_list', to='products.Subcategory', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар не лист',
                'verbose_name_plural': ' Товары не листы',
                'ordering': ['-base_price'],
            },
        ),
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductSpecificationValue',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
