# Generated by Django 2.2.19 on 2023-04-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230322_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вес ед, кг.'),
        ),
    ]
