# Generated by Django 2.2.19 on 2023-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230514_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='Длина'),
        ),
    ]
