# Generated by Django 2.2.19 on 2023-05-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230522_2228'),
        ('products', '0009_auto_20230523_1158'),
    ]

    operations = [
    ]
