# Generated by Django 2.2.19 on 2023-05-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230523_1158'),
        ('products', '0009_auto_20230522_2228'),
    ]

    operations = [
    ]
