# Generated by Django 2.2.19 on 2023-05-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_merge_20230527_1839'),
        ('products', '0010_merge_20230526_1603'),
    ]

    operations = [
    ]
